### ISSUE TITLE
About Code Issues

### ISSUE THREAD

**Issue by xixidongnan** [zsjdddhr/GraphRfi#5]
Is there anyone who has successfully replicated it?

**Comment by zsjdddhr** [comment]
Hi, the Yelp dataset may be not available since 2021. You can contact Shebuti Rayana who is original researcher - [srayana@cs.stonybrook.edu](mailto:srayana@cs.stonybrook.edu) for the yelp dataset. 

The amazon dataset can be found via https://jmcauley.ucsd.edu/data/amazon/.

**Comment by xixidongnan** [comment]
> Hi, the Yelp dataset may be not available since 2021. You can contact Shebuti Rayana who is original researcher - [srayana@cs.stonybrook.edu](mailto:srayana@cs.stonybrook.edu) for the yelp dataset.
> 
> The amazon dataset can be found via https://jmcauley.ucsd.edu/data/amazon/.

Hello, do you have any files for data processing?
